{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "ef0d2692",
   "metadata": {},
   "source": [
    "# BiteMe | Train\n",
    "\n",
    "This notebook includes the most important part of the project - the modelling. The notebook tests methodologies for training, and in it the chosen algorithm is decided. Validation also occurs before final testing, which is conducted in the test notebook. This stage is highly iterative, so all model artefacts, logs and configurations are recorded and saved to disk automatically. This initial setup of what will eventually become MLOps for the final product will be really useful, and helps keep track of what is successful and what isn't.\n",
    "\n",
    "Models to try:\n",
    " - resnet50v2\n",
    " - resnet101v2\n",
    " - resnet152v2\n",
    " - vgg19\n",
    " - densenet169\n",
    " - densenet121\n",
    " - densenet201\n",
    " - inceptionv3\n",
    " - inception_resnetv2\n",
    " - resnext50\n",
    " - resnext101\n",
    " - xception\n",
    " - efficientnet_b0\n",
    " - efficientnet_b1\n",
    " - efficientnet_b2\n",
    " - efficientnet_b3\n",
    " - efficientnet_b4\n",
    " - efficientnet_b5\n",
    "\n",
    "Initial model work is done by using simple, typical image recognition models (CNN architectures) to see how effective these models can be for the problem. Although I don't expect them to be particularly successful, it's important to establish baselines and take a holistic approach to modelling when it's possible.\n",
    "\n",
    "\n",
    "# TODO:\n",
    "\n",
    "Was previously working on dataloader - have to convert labels to one hot encoded!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "be8b5859",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Basic imports\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import os\n",
    "import sys\n",
    "from argparse import ArgumentParser\n",
    "\n",
    "\n",
    "# Data visualisation\n",
    "import matplotlib.pyplot as plt\n",
    "%matplotlib inline\n",
    "import seaborn\n",
    "\n",
    "# Image processing\n",
    "import cv2\n",
    "import albumentations as A\n",
    "import imgaug as ia\n",
    "import imgaug.augmenters as iaa\n",
    "\n",
    "# Model evaluation\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.metrics import accuracy_score, recall_score, precision_score, roc_auc_score, f1_score\n",
    "\n",
    "import torch\n",
    "import pretrainedmodels\n",
    "import pytorch_lightning as pl\n",
    "from pytorch_lightning.callbacks import EarlyStopping, ModelCheckpoint\n",
    "\n",
    "# Local imports\n",
    "sys.path.append(\"..\")\n",
    "from models.models import se_resnet50\n",
    "from utils.loss_function import CrossEntropyLossOneHot\n",
    "from utils.lrs_scheduler import WarmRestart, warm_restart\n",
    "from utils.utils import read_images, augs, get_augs, seed_reproducer, init_logger\n",
    "from utils.constants import *\n",
    "\n",
    "plt.rcParams[\"figure.figsize\"] = (14, 8)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "52a79a8e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>img_name</th>\n",
       "      <th>img_path</th>\n",
       "      <th>label</th>\n",
       "      <th>split</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>7059b14d2aa03ed6c4de11afa32591995181d31c.jpg</td>\n",
       "      <td>../data/cleaned/none/7059b14d2aa03ed6c4de11afa...</td>\n",
       "      <td>none</td>\n",
       "      <td>train</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>ea1b100b581fcdb7ddfae52cc62347a99e304ba4.jpg</td>\n",
       "      <td>../data/cleaned/none/ea1b100b581fcdb7ddfae52cc...</td>\n",
       "      <td>none</td>\n",
       "      <td>train</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>6eac051b9c45ff6821ec8675216f371711b7cea9.jpg</td>\n",
       "      <td>../data/cleaned/none/6eac051b9c45ff6821ec86752...</td>\n",
       "      <td>none</td>\n",
       "      <td>train</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>fc72767f8520df9b2b83941077dc0ee013eb9399.jpg</td>\n",
       "      <td>../data/cleaned/none/fc72767f8520df9b2b8394107...</td>\n",
       "      <td>none</td>\n",
       "      <td>train</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>cf812984268e2aec9a167d3ebe1026f610dd862b.jpg</td>\n",
       "      <td>../data/cleaned/none/cf812984268e2aec9a167d3eb...</td>\n",
       "      <td>none</td>\n",
       "      <td>train</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                       img_name  \\\n",
       "0  7059b14d2aa03ed6c4de11afa32591995181d31c.jpg   \n",
       "1  ea1b100b581fcdb7ddfae52cc62347a99e304ba4.jpg   \n",
       "3  6eac051b9c45ff6821ec8675216f371711b7cea9.jpg   \n",
       "4  fc72767f8520df9b2b83941077dc0ee013eb9399.jpg   \n",
       "5  cf812984268e2aec9a167d3ebe1026f610dd862b.jpg   \n",
       "\n",
       "                                            img_path label  split  \n",
       "0  ../data/cleaned/none/7059b14d2aa03ed6c4de11afa...  none  train  \n",
       "1  ../data/cleaned/none/ea1b100b581fcdb7ddfae52cc...  none  train  \n",
       "3  ../data/cleaned/none/6eac051b9c45ff6821ec86752...  none  train  \n",
       "4  ../data/cleaned/none/fc72767f8520df9b2b8394107...  none  train  \n",
       "5  ../data/cleaned/none/cf812984268e2aec9a167d3eb...  none  train  "
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Define directories\n",
    "base_dir_path = \"../\"\n",
    "\n",
    "data_dir_path = os.path.join(base_dir_path, \"data\")\n",
    "data_preprocessed_dir_path = os.path.join(data_dir_path, \"preprocessed\")\n",
    "data_preprocessed_train_dir_path = os.path.join(data_dir_path, \"preprocessed/train\")\n",
    "\n",
    "data_dir = os.listdir(data_dir_path)\n",
    "data_preprocessed_dir = os.listdir(data_preprocessed_dir_path)\n",
    "data_preprocessed_train_dir = os.listdir(data_preprocessed_train_dir_path)\n",
    "\n",
    "metadata_preprocessed_path = os.path.join(data_preprocessed_dir_path, \"metadata.csv\")\n",
    "metadata = pd.read_csv(metadata_preprocessed_path)\n",
    "# Subset to train only\n",
    "metadata = metadata.loc[metadata.split == \"train\"]\n",
    "\n",
    "metadata.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "a4dde582",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Reading images from: ../data/preprocessed/train\n",
      "Rows set to 512\n",
      "Columns set to 512\n",
      "Channels set to 3\n",
      "Writing images is set to: False\n",
      "Reading images...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 195.45it/s]\n",
      "100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26/26 [00:00<00:00, 103.28it/s]\n",
      "100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 72.68it/s]\n",
      "100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 56.91it/s]\n",
      "100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 45.60it/s]\n",
      "100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 38.54it/s]\n",
      "100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 33.39it/s]\n",
      "100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 29.39it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Image reading complete.\n",
      "Image array shape: (192, 512, 512, 3)\n"
     ]
    }
   ],
   "source": [
    "# Read in train images\n",
    "X_train = read_images(\n",
    "    data_dir_path=data_preprocessed_train_dir_path, \n",
    "    rows=ROWS, \n",
    "    cols=COLS, \n",
    "    channels=CHANNELS, \n",
    "    write_images=False, \n",
    "    output_data_dir_path=None,\n",
    "    verbose=VERBOSE\n",
    ")\n",
    "\n",
    "# Get labels\n",
    "y_train = np.array(metadata[\"label\"])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9b9eb1b2",
   "metadata": {},
   "source": [
    "## Set Parameters"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a2d4a78b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Choose augmentations to use in preprocessing\n",
    "# For full list see helpers.py\n",
    "augs_to_select = [\n",
    "    \"Fliplr\", \n",
    "    \"Flipud\"\n",
    "]\n",
    "# Subset augs based on those selected\n",
    "augs = dict((aug_name, augs[aug_name]) for aug_name in augs_to_select)\n",
    "\n",
    "# Modelling constants - add this to constants.py when needed\n",
    "MODEL_NAME = \"se_resnet50\"\n",
    "MAX_EPOCHS = 6\n",
    "\n",
    "# Create dictionary of configurations used in modelling\n",
    "# this will be updated as modelling progresses if necessary, for logging\n",
    "conf = {\n",
    "    \"device\": \"cuda\" if torch.cuda.device_count() > 0 else \"cpu\",\n",
    "    \"device_name\": torch.cuda.get_device_name(0),\n",
    "    \"n_workers\": 128,\n",
    "    \"rows\": ROWS,\n",
    "    \"cols\": COLS,\n",
    "    \"channels\": CHANNELS,\n",
    "    \"seed\": SEED,\n",
    "    \"n_classes\": len(metadata[\"label\"].unique()),\n",
    "    \"classes\": np.unique(y_train, return_counts=True)[0],\n",
    "    \"class_counts\": np.unique(y_train, return_counts=True)[1],\n",
    "    \"test_size\": TEST_SIZE,\n",
    "    \"num_train_sample\": y_train.shape[0],\n",
    "    \"num_augs\": len(augs),\n",
    "    \"augs\": augs,\n",
    "    \"model_name\": MODEL_NAME,\n",
    "    \"train_batch_size\": 16,\n",
    "    \"val_batch_size\": 16,\n",
    "    \"max_epochs\": MAX_EPOCHS,\n",
    "    \"lr\": 1e-5,\n",
    "    \"optimizer\": \"Adam\",\n",
    "    \"n_splits\": N_SPLITS,\n",
    "    \"precision\": PRECISION,\n",
    "    \"gradient_clip_val\": GRADIENT_CLIP_VAL\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "4ac202af",
   "metadata": {},
   "outputs": [],
   "source": [
    "def init_hparams():\n",
    "    \"\"\"\n",
    "    Initialise hyperparameters for modelling.\n",
    "    \n",
    "    Returns\n",
    "    ---------\n",
    "    hparams : argparse.Namespace\n",
    "        Parsed hyperparameters\n",
    "    \"\"\"\n",
    "    parser = ArgumentParser(add_help=False)\n",
    "    parser.add_argument(\"-backbone\", \"--backbone\", type=str, default=\"se_resnet50\")\n",
    "    parser.add_argument(\"--gpus\", default=[0])\n",
    "    parser.add_argument(\"--n_workers\", type=int, default=conf[\"n_workers\"])\n",
    "    parser.add_argument(\"--image_size\", nargs=\"+\", default=[conf[\"rows\"], conf[\"cols\"]])\n",
    "    parser.add_argument(\"--seed\", type=int, default=conf[\"seed\"])\n",
    "    parser.add_argument(\"--max_epochs\", type=int, default=conf[\"max_epochs\"])\n",
    "    parser.add_argument(\"-tbs\", \"--train_batch_size\", type=int, default=conf[\"train_batch_size\"])\n",
    "    parser.add_argument(\"-vbs\", \"--val_batch_size\", type=int, default=conf[\"val_batch_size\"])\n",
    "    parser.add_argument(\"--n_splits\", type=int, default=conf[\"n_splits\"])\n",
    "    parser.add_argument(\"--precision\", type=int, default=conf[\"precision\"])\n",
    "    parser.add_argument(\"--gradient_clip_val\", type=float, default=conf[\"gradient_clip_val\"])\n",
    "\n",
    "    # This needs more work\n",
    "    parser.add_argument(\"--log_dir\", type=str, default=\"logs\")\n",
    "    \n",
    "    try:\n",
    "        hparams, unknown = parser.parse_known_args()\n",
    "    except:\n",
    "        hparams, unknown = parser.parse_args([])\n",
    "\n",
    "    if len(hparams.gpus) == 1:\n",
    "        hparams.gpus = [int(hparams.gpus[0])]\n",
    "    else:\n",
    "        hparams.gpus = [int(gpu) for gpu in hparams.gpus]\n",
    "\n",
    "    hparams.image_size = [int(size) for size in hparams.image_size]\n",
    "    \n",
    "    return hparams"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "be3abd3c",
   "metadata": {},
   "outputs": [],
   "source": [
    "hparams = init_hparams()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ca739edd",
   "metadata": {},
   "source": [
    "### Create Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "9b5b9c0d",
   "metadata": {},
   "outputs": [],
   "source": [
    "class CoolSystem(pl.LightningModule):\n",
    "    def __init__(self, hparams):\n",
    "        super().__init__()\n",
    "        self.hparams = hparams\n",
    "\n",
    "        seed_reproducer(self.hparams.seed)\n",
    "\n",
    "        self.model = se_resnet50()\n",
    "        self.criterion = CrossEntropyLossOneHot()\n",
    "        self.logger_kun = init_logger(\"kun_in\", hparams.log_dir)\n",
    "\n",
    "    def forward(self, x):\n",
    "        return self.model(x)\n",
    "\n",
    "    def configure_optimizers(self):\n",
    "        self.optimizer = torch.optim.Adam(self.parameters(), lr=0.001, betas=(0.9, 0.999), eps=1e-08, weight_decay=0)\n",
    "        self.scheduler = WarmRestart(self.optimizer, T_max=10, T_mult=1, eta_min=1e-5)\n",
    "        return [self.optimizer], [self.scheduler]\n",
    "\n",
    "    def training_step(self, batch, batch_idx):\n",
    "        step_start_time = time()\n",
    "        images, labels, data_load_time = batch\n",
    "\n",
    "        scores = self(images)\n",
    "        loss = self.criterion(scores, labels)\n",
    "        # self.logger_kun.info(f\"loss : {loss.item()}\")\n",
    "        # ! can only return scalar tensor in training_step\n",
    "        # must return key -> loss\n",
    "        # optional return key -> progress_bar optional (MUST ALL BE TENSORS)\n",
    "        # optional return key -> log optional (MUST ALL BE TENSORS)\n",
    "        data_load_time = torch.sum(data_load_time)\n",
    "\n",
    "        return {\n",
    "            \"loss\": loss,\n",
    "            \"data_load_time\": data_load_time,\n",
    "            \"batch_run_time\": torch.Tensor([time() - step_start_time + data_load_time]).to(data_load_time.device),\n",
    "        }\n",
    "\n",
    "    def training_epoch_end(self, outputs):\n",
    "        # outputs is the return of training_step\n",
    "        train_loss_mean = torch.stack([output[\"loss\"] for output in outputs]).mean()\n",
    "        self.data_load_times = torch.stack([output[\"data_load_time\"] for output in outputs]).sum()\n",
    "        self.batch_run_times = torch.stack([output[\"batch_run_time\"] for output in outputs]).sum()\n",
    "\n",
    "        self.current_epoch += 1\n",
    "        if self.current_epoch < (self.trainer.max_epochs - 4):\n",
    "            self.scheduler = warm_restart(self.scheduler, T_mult=2)\n",
    "\n",
    "        return {\"train_loss\": train_loss_mean}\n",
    "\n",
    "    def validation_step(self, batch, batch_idx):\n",
    "        step_start_time = time()\n",
    "        images, labels, data_load_time = batch\n",
    "        data_load_time = torch.sum(data_load_time)\n",
    "        scores = self(images)\n",
    "        loss = self.criterion(scores, labels)\n",
    "\n",
    "        # must return key -> val_loss\n",
    "        return {\n",
    "            \"val_loss\": loss,\n",
    "            \"scores\": scores,\n",
    "            \"labels\": labels,\n",
    "            \"data_load_time\": data_load_time,\n",
    "            \"batch_run_time\": torch.Tensor([time() - step_start_time + data_load_time]).to(data_load_time.device),\n",
    "        }\n",
    "\n",
    "    def validation_epoch_end(self, outputs):\n",
    "        # compute loss\n",
    "        val_loss_mean = torch.stack([output[\"val_loss\"] for output in outputs]).mean()\n",
    "        self.data_load_times = torch.stack([output[\"data_load_time\"] for output in outputs]).sum()\n",
    "        self.batch_run_times = torch.stack([output[\"batch_run_time\"] for output in outputs]).sum()\n",
    "\n",
    "        # compute roc_auc\n",
    "        scores_all = torch.cat([output[\"scores\"] for output in outputs]).cpu()\n",
    "        labels_all = torch.round(torch.cat([output[\"labels\"] for output in outputs]).cpu())\n",
    "        val_roc_auc = roc_auc_score(labels_all, scores_all)\n",
    "\n",
    "        # terminal logs\n",
    "        self.logger_kun.info(\n",
    "            f\"{self.hparams.fold_i}-{self.current_epoch} | \"\n",
    "            f\"lr : {self.scheduler.get_lr()[0]:.6f} | \"\n",
    "            f\"val_loss : {val_loss_mean:.4f} | \"\n",
    "            f\"val_roc_auc : {val_roc_auc:.4f} | \"\n",
    "            f\"data_load_times : {self.data_load_times:.2f} | \"\n",
    "            f\"batch_run_times : {self.batch_run_times:.2f}\"\n",
    "        )\n",
    "        # f\"data_load_times : {self.data_load_times:.2f} | \"\n",
    "        # f\"batch_run_times : {self.batch_run_times:.2f}\"\n",
    "        # must return key -> val_loss\n",
    "        return {\"val_loss\": val_loss_mean, \"val_roc_auc\": val_roc_auc}"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2dbd3fde",
   "metadata": {},
   "source": [
    "## Cross Validation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1556ab65",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'np' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Input \u001b[0;32mIn [2]\u001b[0m, in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mnp\u001b[49m\u001b[38;5;241m.\u001b[39meye(\u001b[38;5;241m1\u001b[39m)\n",
      "\u001b[0;31mNameError\u001b[0m: name 'np' is not defined"
     ]
    }
   ],
   "source": [
    "np.eye(1)#[targets]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "3672eb71",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array(['none', 'none', 'none', 'none', 'none', 'none', 'none', 'none',\n",
       "       'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none',\n",
       "       'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none',\n",
       "       'none', 'tick', 'tick', 'tick', 'tick', 'tick', 'tick', 'tick',\n",
       "       'tick', 'tick', 'tick', 'tick', 'tick', 'tick', 'tick', 'tick',\n",
       "       'tick', 'tick', 'tick', 'tick', 'tick', 'tick', 'tick', 'tick',\n",
       "       'tick', 'tick', 'tick', 'mite', 'mite', 'mite', 'mite', 'mite',\n",
       "       'mite', 'mite', 'mite', 'mite', 'mite', 'mite', 'mite', 'mite',\n",
       "       'mite', 'mite', 'mite', 'mite', 'mite', 'mite', 'mite', 'mite',\n",
       "       'mosquito', 'mosquito', 'mosquito', 'mosquito', 'mosquito',\n",
       "       'mosquito', 'mosquito', 'mosquito', 'mosquito', 'mosquito',\n",
       "       'mosquito', 'mosquito', 'mosquito', 'mosquito', 'mosquito',\n",
       "       'mosquito', 'mosquito', 'mosquito', 'mosquito', 'mosquito',\n",
       "       'mosquito', 'mosquito', 'mosquito', 'mosquito', 'mosquito',\n",
       "       'horsefly', 'horsefly', 'horsefly', 'horsefly', 'horsefly',\n",
       "       'horsefly', 'horsefly', 'horsefly', 'horsefly', 'horsefly',\n",
       "       'horsefly', 'horsefly', 'horsefly', 'horsefly', 'horsefly',\n",
       "       'horsefly', 'horsefly', 'horsefly', 'horsefly', 'horsefly',\n",
       "       'horsefly', 'horsefly', 'horsefly', 'horsefly', 'horsefly', 'bee',\n",
       "       'bee', 'bee', 'bee', 'bee', 'bee', 'bee', 'bee', 'bee', 'bee',\n",
       "       'bee', 'bee', 'bee', 'bee', 'bee', 'bee', 'bee', 'bee', 'bee',\n",
       "       'bee', 'bee', 'bee', 'bedbug', 'bedbug', 'bedbug', 'bedbug',\n",
       "       'bedbug', 'bedbug', 'bedbug', 'bedbug', 'bedbug', 'bedbug',\n",
       "       'bedbug', 'bedbug', 'bedbug', 'bedbug', 'bedbug', 'bedbug',\n",
       "       'bedbug', 'bedbug', 'bedbug', 'bedbug', 'bedbug', 'bedbug',\n",
       "       'bedbug', 'bedbug', 'bedbug', 'ant', 'ant', 'ant', 'ant', 'ant',\n",
       "       'ant', 'ant', 'ant', 'ant', 'ant', 'ant', 'ant', 'ant', 'ant',\n",
       "       'ant', 'ant', 'ant', 'ant', 'ant', 'ant', 'ant', 'ant', 'ant'],\n",
       "      dtype=object)"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y_train"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "cd4d2995",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Split cross validation idx\n",
    "# Subset images and labels for cross validation\n",
    "# Create image augmentations and additional labels\n",
    "# Read in pretrained weights\n",
    "# Any additional layers\n",
    "# Create model instance\n",
    "# Create error metric\n",
    "# Run training\n",
    "# Make val predictions\n",
    "# Val error metric\n",
    "# Create directory for instance\n",
    "# Save model\n",
    "# Save log and config \n",
    "# Append train/val errors to csv"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "ada421fa",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'index' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Input \u001b[0;32mIn [16]\u001b[0m, in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0m train_data\u001b[38;5;241m.\u001b[39miloc[\u001b[43mindex\u001b[49m, \u001b[38;5;241m0\u001b[39m]\n",
      "\u001b[0;31mNameError\u001b[0m: name 'index' is not defined"
     ]
    }
   ],
   "source": [
    "train_data#.iloc[index, 0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ad6679b0",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fd2267d4a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/site-packages/torch/utils/data/dataloader.py\", line 1328, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/site-packages/torch/utils/data/dataloader.py\", line 1268, in _shutdown_workers\n",
      "    if not self._shutdown:\n",
      "AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_shutdown'\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fd2267d4a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/site-packages/torch/utils/data/dataloader.py\", line 1328, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/site-packages/torch/utils/data/dataloader.py\", line 1301, in _shutdown_workers\n",
      "    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/process.py\", line 149, in join\n",
      "    res = self._popen.wait(timeout)\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/popen_fork.py\", line 40, in wait\n",
      "    if not wait([self.sentinel], timeout):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 936, in wait\n",
      "    ready = selector.select(timeout)\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/selectors.py\", line 416, in select\n",
      "    fd_event_list = self._selector.poll(timeout)\n",
      "KeyboardInterrupt: \n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    result = self._recv_bytes()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 910, in run\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self.run()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 910, in run\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 272, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "    result = self._recv_bytes()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 272, in _feed\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "    # Return True if lock is owned by current_thread.\n",
      "ValueError: semaphore or lock released too many times\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "Exception in thread QueueFeederThread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/queues.py\", line 241, in _feed\n",
      "    result = self._recv_bytes()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    queue_sem.release()\n",
      "ValueError: semaphore or lock released too many times\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "    result = self._recv_bytes()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    result = self._recv_bytes()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    _close(self._handle)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "    close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 182, in close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n",
      "    self._close()\n",
      "  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/multiprocessing/connection.py\", line 366, in _close\n"
     ]
    }
   ],
   "source": [
    "cv2.cvtColor(\n",
    "            cv2.imread(train_data.iloc[index, 0]), \n",
    "            cv2.COLOR_BGR2RGB\n",
    "        )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0f11f484",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "37cf021e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from time import time\n",
    "\n",
    "# Third party libraries\n",
    "import cv2\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import torch\n",
    "from albumentations import Compose, Normalize, Resize\n",
    "\n",
    "from torch.utils.data import DataLoader, Dataset\n",
    "\n",
    "\n",
    "class BiteDataset(Dataset):\n",
    "    \"\"\" \n",
    "    ADD DOCSTRING\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, data, transforms=None):\n",
    "        self.data = data\n",
    "        self.transforms = transforms\n",
    "\n",
    "    def __getitem__(self, index):\n",
    "        start_time = time()\n",
    "        # Read image\n",
    "        image = cv2.cvtColor(\n",
    "            cv2.imread(self.data.iloc[index, 0]), \n",
    "            cv2.COLOR_BGR2RGB\n",
    "        )\n",
    "\n",
    "        # Convert if not the right shape\n",
    "        if image.shape != IMG_SHAPE:\n",
    "            image = image.transpose(1, 0, 2)\n",
    "\n",
    "        # Perform augmentation\n",
    "        if self.transforms is not None:\n",
    "            image = self.transforms(image=image)[\"image\"].transpose(2, 0, 1)\n",
    "\n",
    "        label = torch.FloatTensor(self.data.iloc[index, 1].values.astype(np.int64))\n",
    "        print(image)\n",
    "        print(label)\n",
    "        \n",
    "        \n",
    "        return image, label, time() - start_time\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.data)\n",
    "\n",
    "\n",
    "def generate_transforms(image_size):\n",
    "    \"\"\"\n",
    "    ADD DOCSTRING\n",
    "    \"\"\"\n",
    "\n",
    "    train_transform = Compose(\n",
    "        [\n",
    "            Resize(height=image_size[0], width=image_size[1]),\n",
    "            #OneOf([RandomBrightness(limit=0.1, p=1), RandomContrast(limit=0.1, p=1)]),\n",
    "            #OneOf([MotionBlur(blur_limit=3), MedianBlur(blur_limit=3), GaussianBlur(blur_limit=3)], p=0.5),\n",
    "            #VerticalFlip(p=0.5),\n",
    "            #HorizontalFlip(p=0.5),\n",
    "            #ShiftScaleRotate(\n",
    "            #    shift_limit=0.2,\n",
    "            #    scale_limit=0.2,\n",
    "            #    rotate_limit=20,\n",
    "            #    interpolation=cv2.INTER_LINEAR,\n",
    "            #    border_mode=cv2.BORDER_REFLECT_101,\n",
    "            #    p=1,\n",
    "            #),\n",
    "            Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225), max_pixel_value=255.0, p=1.0),\n",
    "        ]\n",
    "    )\n",
    "\n",
    "    val_transform = Compose(\n",
    "        [\n",
    "            Resize(height=image_size[0], width=image_size[1]),\n",
    "            Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225), max_pixel_value=255.0, p=1.0),\n",
    "        ]\n",
    "    )\n",
    "\n",
    "    return {\"train_transforms\": train_transform, \"val_transforms\": val_transform}\n",
    "\n",
    "\n",
    "def generate_dataloaders(hparams, train_data, val_data, transforms):\n",
    "    \"\"\"\n",
    "    ADD DOCSTRING\n",
    "    \"\"\"\n",
    "    \n",
    "    train_dataset = BiteDataset(\n",
    "        data=train_data, transforms=None\n",
    "    )\n",
    "    \n",
    "    val_dataset = BiteDataset(\n",
    "        data=val_data, transforms=None\n",
    "    )\n",
    "    \n",
    "    train_dataloader = DataLoader(\n",
    "        train_dataset,\n",
    "        batch_size=hparams.train_batch_size,\n",
    "        shuffle=True,\n",
    "        num_workers=hparams.n_workers,\n",
    "        pin_memory=True,\n",
    "        drop_last=True,\n",
    "    )\n",
    "    \n",
    "    val_dataloader = DataLoader(\n",
    "        val_dataset,\n",
    "        batch_size=hparams.val_batch_size,\n",
    "        shuffle=False,\n",
    "        num_workers=hparams.n_workers,\n",
    "        pin_memory=True,\n",
    "        drop_last=False,\n",
    "    )\n",
    "\n",
    "    return train_dataloader, val_dataloader"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ca29413c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "94c68f6c",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "GPU available: True, used: True\n",
      "TPU available: False, using: 0 TPU cores\n",
      "CUDA_VISIBLE_DEVICES: [0]\n",
      "Using native 16bit precision.\n",
      "[ WARN:0@209.217] global /home/conda/feedstock_root/build_artifacts/libopencv_1654062669265/work/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('ff05114ed0314e63fe19e4fcade287d3207b3438.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@209.217] global /home/conda/feedstock_root/build_artifacts/libopencv_1654062669265/work/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('8f578f71581bbb75e78b56318c7f3c924ad8380b.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@209.217] global /home/conda/feedstock_root/build_artifacts/libopencv_1654062669265/work/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('6c47b92ec8500adbc823b2e520f5c87a31c65244.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@209.218] global /home/conda/feedstock_root/build_artifacts/libopencv_1654062669265/work/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('1c62b7373b0ec3a6d39d4cb53f05ddfd6974d01d.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@209.220] global /home/conda/feedstock_root/build_artifacts/libopencv_1654062669265/work/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('22a6c034d8c928cdce93baf77312e964f6a8ae6f.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@209.220] global /home/conda/feedstock_root/build_artifacts/libopencv_1654062669265/work/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('e598c9524b7fa78a9d58e63f208de2ea1351b0b3.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@209.220] global /home/conda/feedstock_root/build_artifacts/libopencv_1654062669265/work/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('d2d4a895faa8c2f9d5a079666ad1495e81001325.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@209.221] global /home/conda/feedstock_root/build_artifacts/libopencv_1654062669265/work/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('c97b65728d7d3f485976ea2016ff7bb7a1855f9c.jpg'): can't open/read file: check file path/integrity\n"
     ]
    },
    {
     "ename": "error",
     "evalue": "Caught error in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py\", line 287, in _worker_loop\n    data = fetcher.fetch(index)\n  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py\", line 49, in fetch\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py\", line 49, in <listcomp>\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File \"/tmp/ipykernel_29515/3780588977.py\", line 26, in __getitem__\n    image = cv2.cvtColor(\ncv2.error: OpenCV(4.5.5) /home/conda/feedstock_root/build_artifacts/libopencv_1654062669265/work/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31merror\u001b[0m                                     Traceback (most recent call last)",
      "Input \u001b[0;32mIn [14]\u001b[0m, in \u001b[0;36m<cell line: 7>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     32\u001b[0m model \u001b[38;5;241m=\u001b[39m CoolSystem(hparams)\n\u001b[1;32m     33\u001b[0m trainer \u001b[38;5;241m=\u001b[39m pl\u001b[38;5;241m.\u001b[39mTrainer(\n\u001b[1;32m     34\u001b[0m     gpus\u001b[38;5;241m=\u001b[39mhparams\u001b[38;5;241m.\u001b[39mgpus,\n\u001b[1;32m     35\u001b[0m     min_epochs\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m2\u001b[39m,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     44\u001b[0m     gradient_clip_val\u001b[38;5;241m=\u001b[39mhparams\u001b[38;5;241m.\u001b[39mgradient_clip_val,\n\u001b[1;32m     45\u001b[0m )\n\u001b[0;32m---> 46\u001b[0m \u001b[43mtrainer\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmodel\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtrain_dataloader\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mval_dataloader\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     48\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m-\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m*\u001b[39m\u001b[38;5;241m40\u001b[39m)\n",
      "File \u001b[0;32m~/miniconda3/envs/biteme/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:1003\u001b[0m, in \u001b[0;36mTrainer.fit\u001b[0;34m(self, model, train_dataloader, val_dataloaders)\u001b[0m\n\u001b[1;32m   1000\u001b[0m     results \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mhorovod_train(model)\n\u001b[1;32m   1002\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msingle_gpu:\n\u001b[0;32m-> 1003\u001b[0m     results \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msingle_gpu_train\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmodel\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1005\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39muse_tpu:  \u001b[38;5;66;03m# pragma: no-cover\u001b[39;00m\n\u001b[1;32m   1006\u001b[0m     rank_zero_info(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtraining on \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mtpu_cores\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m TPU cores\u001b[39m\u001b[38;5;124m'\u001b[39m)\n",
      "File \u001b[0;32m~/miniconda3/envs/biteme/lib/python3.9/site-packages/pytorch_lightning/trainer/distrib_parts.py:186\u001b[0m, in \u001b[0;36mTrainerDPMixin.single_gpu_train\u001b[0;34m(self, model)\u001b[0m\n\u001b[1;32m    183\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39moptimizers \u001b[38;5;241m=\u001b[39m optimizers\n\u001b[1;32m    184\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mreinit_scheduler_properties(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39moptimizers, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mlr_schedulers)\n\u001b[0;32m--> 186\u001b[0m results \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun_pretrain_routine\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmodel\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    187\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m results\n",
      "File \u001b[0;32m~/miniconda3/envs/biteme/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:1213\u001b[0m, in \u001b[0;36mTrainer.run_pretrain_routine\u001b[0;34m(self, model)\u001b[0m\n\u001b[1;32m   1210\u001b[0m         torch\u001b[38;5;241m.\u001b[39mcuda\u001b[38;5;241m.\u001b[39mempty_cache()\n\u001b[1;32m   1212\u001b[0m \u001b[38;5;66;03m# CORE TRAINING LOOP\u001b[39;00m\n\u001b[0;32m-> 1213\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mtrain\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/envs/biteme/lib/python3.9/site-packages/pytorch_lightning/trainer/training_loop.py:370\u001b[0m, in \u001b[0;36mTrainerTrainLoopMixin.train\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    363\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mbatch_loss_value \u001b[38;5;241m=\u001b[39m TensorRunningAccum(\n\u001b[1;32m    364\u001b[0m     window_length\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39maccumulate_grad_batches\n\u001b[1;32m    365\u001b[0m )\n\u001b[1;32m    367\u001b[0m \u001b[38;5;66;03m# -----------------\u001b[39;00m\n\u001b[1;32m    368\u001b[0m \u001b[38;5;66;03m# RUN TNG EPOCH\u001b[39;00m\n\u001b[1;32m    369\u001b[0m \u001b[38;5;66;03m# -----------------\u001b[39;00m\n\u001b[0;32m--> 370\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun_training_epoch\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    372\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmax_steps \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmax_steps \u001b[38;5;241m<\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mglobal_step:\n\u001b[1;32m    373\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mrun_training_teardown()\n",
      "File \u001b[0;32m~/miniconda3/envs/biteme/lib/python3.9/site-packages/pytorch_lightning/trainer/training_loop.py:439\u001b[0m, in \u001b[0;36mTrainerTrainLoopMixin.run_training_epoch\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    436\u001b[0m should_check_val \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[1;32m    438\u001b[0m \u001b[38;5;66;03m# run epoch\u001b[39;00m\n\u001b[0;32m--> 439\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m batch_idx, (batch, is_last_batch) \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mprofiler\u001b[38;5;241m.\u001b[39mprofile_iterable(\n\u001b[1;32m    440\u001b[0m         \u001b[38;5;28menumerate\u001b[39m(_with_is_last(train_dataloader)), \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mget_train_batch\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    441\u001b[0m ):\n\u001b[1;32m    442\u001b[0m     \u001b[38;5;66;03m# stop epoch if we limited the number of training batches\u001b[39;00m\n\u001b[1;32m    443\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m batch_idx \u001b[38;5;241m>\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mnum_training_batches:\n\u001b[1;32m    444\u001b[0m         \u001b[38;5;28;01mbreak\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/biteme/lib/python3.9/site-packages/pytorch_lightning/profiler/profilers.py:64\u001b[0m, in \u001b[0;36mBaseProfiler.profile_iterable\u001b[0;34m(self, iterable, action_name)\u001b[0m\n\u001b[1;32m     62\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     63\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mstart(action_name)\n\u001b[0;32m---> 64\u001b[0m     value \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mnext\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43miterator\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     65\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mstop(action_name)\n\u001b[1;32m     66\u001b[0m     \u001b[38;5;28;01myield\u001b[39;00m value\n",
      "File \u001b[0;32m~/miniconda3/envs/biteme/lib/python3.9/site-packages/pytorch_lightning/trainer/training_loop.py:1012\u001b[0m, in \u001b[0;36m_with_is_last\u001b[0;34m(iterable)\u001b[0m\n\u001b[1;32m   1009\u001b[0m \u001b[38;5;124;03m\"\"\"Pass through values from the given iterable with an added boolean indicating if this is the last item.\u001b[39;00m\n\u001b[1;32m   1010\u001b[0m \u001b[38;5;124;03mSee `https://stackoverflow.com/a/1630350 <https://stackoverflow.com/a/1630350>`_\"\"\"\u001b[39;00m\n\u001b[1;32m   1011\u001b[0m it \u001b[38;5;241m=\u001b[39m \u001b[38;5;28miter\u001b[39m(iterable)\n\u001b[0;32m-> 1012\u001b[0m last \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mnext\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mit\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1013\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m val \u001b[38;5;129;01min\u001b[39;00m it:\n\u001b[1;32m   1014\u001b[0m     \u001b[38;5;66;03m# yield last and has next\u001b[39;00m\n\u001b[1;32m   1015\u001b[0m     \u001b[38;5;28;01myield\u001b[39;00m last, \u001b[38;5;28;01mFalse\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/biteme/lib/python3.9/site-packages/torch/utils/data/dataloader.py:521\u001b[0m, in \u001b[0;36m_BaseDataLoaderIter.__next__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    519\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_sampler_iter \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    520\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_reset()\n\u001b[0;32m--> 521\u001b[0m data \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_next_data\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    522\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_num_yielded \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m1\u001b[39m\n\u001b[1;32m    523\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_dataset_kind \u001b[38;5;241m==\u001b[39m _DatasetKind\u001b[38;5;241m.\u001b[39mIterable \u001b[38;5;129;01mand\u001b[39;00m \\\n\u001b[1;32m    524\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_IterableDataset_len_called \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mand\u001b[39;00m \\\n\u001b[1;32m    525\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_num_yielded \u001b[38;5;241m>\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_IterableDataset_len_called:\n",
      "File \u001b[0;32m~/miniconda3/envs/biteme/lib/python3.9/site-packages/torch/utils/data/dataloader.py:1203\u001b[0m, in \u001b[0;36m_MultiProcessingDataLoaderIter._next_data\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1201\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m   1202\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_task_info[idx]\n\u001b[0;32m-> 1203\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_process_data\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdata\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/envs/biteme/lib/python3.9/site-packages/torch/utils/data/dataloader.py:1229\u001b[0m, in \u001b[0;36m_MultiProcessingDataLoaderIter._process_data\u001b[0;34m(self, data)\u001b[0m\n\u001b[1;32m   1227\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_try_put_index()\n\u001b[1;32m   1228\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(data, ExceptionWrapper):\n\u001b[0;32m-> 1229\u001b[0m     \u001b[43mdata\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mreraise\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1230\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m data\n",
      "File \u001b[0;32m~/miniconda3/envs/biteme/lib/python3.9/site-packages/torch/_utils.py:434\u001b[0m, in \u001b[0;36mExceptionWrapper.reraise\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    430\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m:\n\u001b[1;32m    431\u001b[0m     \u001b[38;5;66;03m# If the exception takes multiple arguments, don't try to\u001b[39;00m\n\u001b[1;32m    432\u001b[0m     \u001b[38;5;66;03m# instantiate since we don't know how to\u001b[39;00m\n\u001b[1;32m    433\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(msg) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28mNone\u001b[39m\n\u001b[0;32m--> 434\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m exception\n",
      "\u001b[0;31merror\u001b[0m: Caught error in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py\", line 287, in _worker_loop\n    data = fetcher.fetch(index)\n  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py\", line 49, in fetch\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File \"/home/edwardsims/miniconda3/envs/biteme/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py\", line 49, in <listcomp>\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File \"/tmp/ipykernel_29515/3780588977.py\", line 26, in __getitem__\n    image = cv2.cvtColor(\ncv2.error: OpenCV(4.5.5) /home/conda/feedstock_root/build_artifacts/libopencv_1654062669265/work/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'\n\n"
     ]
    }
   ],
   "source": [
    "# List for validation scores \n",
    "valid_roc_auc_scores = []\n",
    "# Initialise cross validation\n",
    "folds = StratifiedKFold(n_splits=3, shuffle=True, random_state=hparams.seed)\n",
    "\n",
    "# Start cross validation\n",
    "for fold_i, (train_index, val_index) in enumerate(folds.split(metadata, y_train)):\n",
    "    hparams.fold_i = fold_i\n",
    "    # Split train images and validation sets\n",
    "    train_data = metadata.iloc[train_index, :].reset_index(drop=True)\n",
    "    val_data = metadata.iloc[val_index, :].reset_index(drop=True)\n",
    "    \n",
    "    train_dataloader, val_dataloader = generate_dataloaders(hparams, train_data, val_data, None)\n",
    "    \n",
    "    # TO REMOVE\n",
    "    epoch=1\n",
    "    val_loss=20\n",
    "    val_roc_auc=25\n",
    "    # TO REMOVE\n",
    "    \n",
    "    checkpoint_callback = ModelCheckpoint(\n",
    "        monitor=\"val_roc_auc\",\n",
    "        save_top_k=6,\n",
    "        mode=\"max\",\n",
    "        filepath=os.path.join(hparams.log_dir, f\"fold={fold_i}\" + \"-{epoch}-{val_loss:.4f}-{val_roc_auc:.4f}\")\n",
    "    )\n",
    "    \n",
    "    \n",
    "    early_stop_callback = EarlyStopping(monitor=\"val_roc_auc\", patience=10, mode=\"max\", verbose=True)\n",
    "    \n",
    "    # Instance Model, Trainer and train model\n",
    "    model = CoolSystem(hparams)\n",
    "    trainer = pl.Trainer(\n",
    "        gpus=hparams.gpus,\n",
    "        min_epochs=2,\n",
    "        max_epochs=hparams.max_epochs,\n",
    "        early_stop_callback=early_stop_callback,\n",
    "        checkpoint_callback=checkpoint_callback,\n",
    "        progress_bar_refresh_rate=0,\n",
    "        precision=hparams.precision,\n",
    "        num_sanity_val_steps=0,\n",
    "        profiler=False,\n",
    "        weights_summary=None,\n",
    "        gradient_clip_val=hparams.gradient_clip_val,\n",
    "    )\n",
    "    trainer.fit(model, train_dataloader, val_dataloader)\n",
    "    \n",
    "    print(\"-\"*40)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "21553dc0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fb5ed366",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "75dc226a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e151cf72",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0ea1c801",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "465a643c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ac3ee915",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b120d42b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "86b97c59",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "27330df1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8fbf9676",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "06e8f7d8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch.nn as nn\n",
    "nn.Sequential(\n",
    "    pretrainedmodels.__dict__[\"se_resnet50\"]\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e31ac9e0",
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "pretrainedmodels.__dict__[\"se_resnet50\"](num_classes=1000, pretrained='imagenet')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e0eb9129",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "20db3ffb",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "biteme",
   "language": "python",
   "name": "biteme"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
